/* ============================================================
 * 单词检测 · 词表管理
 * ------------------------------------------------------------
 * 9 个教材版本。目前每版先用“通用衔接词表”占位，
 * 把每个版本的真实词表发给我，我直接替换对应数组即可。
 *
 * 词表格式：每项 { en:"英文", zh:"中文" }
 * 想自己改：直接编辑下面 WORD_LISTS 里对应版本那一行的数组。
 * ============================================================ */

const DEFAULT_WORDS = [
  {en:"apple",zh:"苹果"},{en:"banana",zh:"香蕉"},{en:"book",zh:"书"},
  {en:"pen",zh:"钢笔"},{en:"pencil",zh:"铅笔"},{en:"school",zh:"学校"},
  {en:"teacher",zh:"老师"},{en:"student",zh:"学生"},{en:"friend",zh:"朋友"},
  {en:"family",zh:"家庭"},{en:"father",zh:"父亲"},{en:"mother",zh:"母亲"},
  {en:"happy",zh:"快乐的"},{en:"sad",zh:"悲伤的"},{en:"big",zh:"大的"},
  {en:"small",zh:"小的"},{en:"red",zh:"红色"},{en:"blue",zh:"蓝色"},
  {en:"green",zh:"绿色"},{en:"yellow",zh:"黄色"},{en:"cat",zh:"猫"},
  {en:"dog",zh:"狗"},{en:"bird",zh:"鸟"},{en:"fish",zh:"鱼"},
  {en:"tree",zh:"树"},{en:"flower",zh:"花"},{en:"water",zh:"水"},
  {en:"milk",zh:"牛奶"},{en:"food",zh:"食物"},{en:"morning",zh:"早晨"},
  {en:"evening",zh:"晚上"},{en:"play",zh:"玩"},{en:"read",zh:"读"},
  {en:"write",zh:"写"},{en:"eat",zh:"吃"},{en:"drink",zh:"喝"},
  {en:"run",zh:"跑"},{en:"sing",zh:"唱歌"},{en:"English",zh:"英语"},
  {en:"number",zh:"数字"},{en:"color",zh:"颜色"},{en:"name",zh:"名字"},
  {en:"good",zh:"好的"},{en:"new",zh:"新的"}
];

/* TODO：把下面的版本数组替换成各版本真实词表
 * 例： "人教版": [ {en:"hello",zh:"你好"}, ... ],
 */
const WORD_LISTS = {
  "人教版": [
    {en:"at the back (of)",zh:"在（……）后面"},{en:"corner",zh:"墙角；街角"},
    {en:"bookcase",zh:"书架；书柜"},{en:"screen",zh:"屏幕；银幕"},
    {en:"at school",zh:"在学校"},{en:"different from",zh:"与……不一样"},
    {en:"modern",zh:"现代的；当代的"},{en:"do exercises",zh:"做体操"},
    {en:"amazing",zh:"令人惊奇（惊喜或惊叹）的"},{en:"raise",zh:"使升高；提高"},
    {en:"flag",zh:"旗；旗帜"},{en:"most",zh:"大多数；最多；最"},
    {en:"change",zh:"改变；变化"},{en:"seat",zh:"座位"},
    {en:"delicious",zh:"美味的；可口的"},{en:"How about",zh:"……怎么样？"},
    {en:"yours",zh:"你的；您的"},{en:"send",zh:"发送；邮寄"},
    {en:"similar",zh:"类似的；相像的"},{en:"similar to",zh:"类似于；相像的"},
    {en:"sound",zh:"听起来；声音；响声"},{en:"bye for now",zh:"再见"},
    {en:"Flora",zh:"弗洛拉（人名）"},{en:"useful",zh:"有用的；有益的"},
    {en:"exciting",zh:"令人激动的；使人兴奋的"},{en:"past",zh:"过去；过去的；在……之后"},
    {en:"good with",zh:"灵巧的；善于应付……的"},{en:"number",zh:"数字；号码"},
    {en:"help sb. with sth.",zh:"帮助某人做某事"},{en:"reason",zh:"原因；理由"},
    {en:"listen to",zh:"听；倾听"},{en:"good at",zh:"擅长"},
    {en:"remember",zh:"记住；记起"},{en:"as",zh:"如同；作为；当……时；由于"},
    {en:"AM",zh:"上午"},{en:"PM",zh:"下午；午后"},
    {en:"French",zh:"法国的；法国人的；法语的"},{en:"excellent",zh:"优秀的；极好的"},
    {en:"instrument",zh:"乐器；器械；工具"},{en:"singer",zh:"歌手"},
    {en:"future",zh:"将来；未来"},{en:"in the future",zh:"将来；未来"},
    {en:"term",zh:"学期"},{en:"work out",zh:"计算出；解决"},
    {en:"problem",zh:"难题；困难"},{en:"in class",zh:"课堂上"},
    {en:"magic",zh:"魔法；魔力；魔术"},{en:"life",zh:"生活；生命"},
    {en:"biology",zh:"生物学"},{en:"IT",zh:"信息技术"}
  ],
  "沪教五四": [
    {en:"entertain",zh:"使快乐；娱乐"},{en:"audience",zh:"观众"},
    {en:"set",zh:"摄影场"},{en:"role",zh:"角色"},
    {en:"scene",zh:"现场；场景"},{en:"arrive",zh:"到达"},
    {en:"page",zh:"（书刊或纸张的）页"},{en:"knowledge",zh:"知识；学问"},
    {en:"biology",zh:"生物学"},{en:"education",zh:"教育"},
    {en:"above",zh:"（水平）超过；更多；更大"},{en:"readiness",zh:"乐意"},
    {en:"communication",zh:"交流；交际"},{en:"training",zh:"训练；培训"},
    {en:"taste",zh:"品尝"},{en:"maybe",zh:"可能；也许"},
    {en:"customer",zh:"顾客；客户"},{en:"market",zh:"市场；集市"},
    {en:"everything",zh:"每样事物"},{en:"fresh",zh:"新鲜的"},
    {en:"restaurant",zh:"餐厅"},{en:"pride",zh:"骄傲；自豪"},
    {en:"kilometre",zh:"千米；公里"},{en:"exactly",zh:"确切地；精确地；恰好"},
    {en:"ever",zh:"在任何时候；从来"},{en:"centre",zh:"中心"},
    {en:"greet",zh:"打招呼；欢迎；迎接"},{en:"distance",zh:"距离"},
    {en:"method",zh:"方法；措施"},{en:"simple",zh:"简单的"},
    {en:"railway",zh:"铁路；铁道"},{en:"eachother",zh:"相互；彼此"},
    {en:"address",zh:"地址"},{en:"deliver",zh:"递送"},
    {en:"serve",zh:"服务"},{en:"trust",zh:"信任；信赖"},
    {en:"respect",zh:"尊重；敬重"},{en:"lively",zh:"活泼的；活跃的"},
    {en:"dictionary",zh:"字典；词典"},{en:"throw",zh:"扔；掷"},
    {en:"camera",zh:"照相机；摄影机"},{en:"itself",zh:"它自己（的反身形式）"},
    {en:"alarm",zh:"警报器"},{en:"stranger",zh:"陌生人"},
    {en:"lock",zh:"锁"},{en:"explore",zh:"探索；探究"},
    {en:"rock",zh:"（使）轻轻摇晃"},{en:"shower",zh:"淋浴"},
    {en:"mode",zh:"模式；方式"},{en:"textmessage",zh:"（手机）短信息"}
  ],
  "冀教": [
    {en:"laugh",zh:"笑；大笑"},{en:"present",zh:"礼物；礼品"},
    {en:"smile",zh:"微笑；笑"},{en:"away",zh:"去别处；离开"},
    {en:"set",zh:"放置；设置"},{en:"point",zh:"指向；瞄准"},
    {en:"secret",zh:"秘密；诀窍；奥妙"},{en:"end",zh:"结束；末端"},
    {en:"finally",zh:"终于；最终"},{en:"tiny",zh:"微小的；极小的"},
    {en:"crayon",zh:"蜡笔"},{en:"cover",zh:"封皮；覆盖物"},
    {en:"something",zh:"某物；某事"},{en:"rose",zh:"玫瑰花；蔷薇花"},
    {en:"sky",zh:"天；天空"},{en:"poem",zh:"诗"},
    {en:"riddle",zh:"谜；谜语"},{en:"soft",zh:"软的；细滑的；柔和的"},
    {en:"sofa",zh:"长沙发"},{en:"business",zh:"商务；商业"},
    {en:"donut",zh:"甜甜圈"},{en:"pity",zh:"可惜；遗憾；同情"},
    {en:"friendly",zh:"友好的"},{en:"loyal",zh:"忠诚的；忠实的"},
    {en:"rhino",zh:"犀牛"},{en:"eagle",zh:"鹰"},
    {en:"team",zh:"队；组"},{en:"each",zh:"各自；每个"},
    {en:"skin",zh:"毛皮；皮肤；皮"},{en:"stay",zh:"保持；待；暂住"},
    {en:"sound",zh:"声音；响声"},{en:"dangerous",zh:"有危险的"},
    {en:"thing",zh:"事情；东西"},{en:"nearby",zh:"在附近；不远"},
    {en:"scare",zh:"惊吓；使害怕"},{en:"insect",zh:"昆虫"},
    {en:"cheese",zh:"奶酪"},{en:"butter",zh:"黄油；奶油"},
    {en:"feed",zh:"喂养；饲养"},{en:"sign",zh:"标牌；标志；迹象"},
    {en:"giraffe",zh:"长颈鹿"},{en:"bamboo",zh:"竹；竹子"},
    {en:"instead",zh:"代替；反而"},{en:"carrot",zh:"胡萝卜"},
    {en:"funny",zh:"滑稽的；好笑的"},{en:"dinosaur",zh:"恐龙"},
    {en:"report",zh:"报告；报道"},{en:"fat",zh:"肥的；肥胖的"},
    {en:"hairy",zh:"多毛的"},{en:"most",zh:"大多数；最多"}
  ],
  "北师大": [
    {en:"pencilcase",zh:"铅笔盒"},{en:"everything",zh:"每件事；所有事物；一切"},
    {en:"ready",zh:"准备好；准备完毕"},{en:"check",zh:"检查；核查"},
    {en:"dining",zh:"进餐；用餐；吃饭"},{en:"hall",zh:"礼堂；大厅"},
    {en:"dininghall",zh:"餐厅"},{en:"lab",zh:"实验室"},
    {en:"field",zh:"运动场；田地；场地"},{en:"gym",zh:"体育馆；健身房"},
    {en:"headteacher",zh:"(中小学)校长"},{en:"experiment",zh:"实验；试验"},
    {en:"skill",zh:"技能；技术"},{en:"special",zh:"特殊的；特别的"},
    {en:"Monday",zh:"星期一"},{en:"Tuesday",zh:"星期二"},
    {en:"outside",zh:"在外面；外部"},{en:"during",zh:"在……期间"},
    {en:"enjoy",zh:"享受……的乐趣；欣赏；喜爱"},{en:"howmany",zh:"多少（后接可数名词复数）"},
    {en:"everyday",zh:"每天"},{en:"tennis",zh:"网球"},
    {en:"blog",zh:"博客"},{en:"post",zh:"帖子；发布；邮寄"},
    {en:"excuse",zh:"原谅；宽恕"},{en:"Excuse me",zh:"劳驾；请原谅"},
    {en:"carry",zh:"拿；提；搬"},{en:"weekday",zh:"工作日"},
    {en:"furniture",zh:"家具"},{en:"equipment",zh:"设备；器材"},
    {en:"livingroom",zh:"客厅；起居室"},{en:"bathroom",zh:"浴室；洗手间；卫生间"},
    {en:"bedroom",zh:"卧室"},{en:"bookcase",zh:"书架；书柜"},
    {en:"machine",zh:"机器；机械装置"},{en:"fridge",zh:"冰箱"},
    {en:"cooker",zh:"厨灶；炉具"},{en:"sofa",zh:"长沙发"},
    {en:"flat",zh:"公寓；单元房"},{en:"sound",zh:"听起来好像；声音；响声"},
    {en:"thing",zh:"物件；物品；事物"},{en:"shower",zh:"淋浴器；淋浴间；淋浴"},
    {en:"comfortable",zh:"使人舒服的；舒适的"},{en:"cream",zh:"奶油色的；奶油；乳脂"},
    {en:"allkindsof",zh:"各种各样"},{en:"inside",zh:"在……里面；里面；内部"},
    {en:"dictionary",zh:"词典；字典；辞书"},{en:"bookshelf",zh:"书架"},
    {en:"nextto",zh:"紧邻；在……近旁"},{en:"need",zh:"需要"}
  ],
  "仁爱版":   [
    {en:"question",zh:"问题"},{en:"short",zh:"短的；矮的"},
    {en:"strong",zh:"强壮的；强烈的"},{en:"thin",zh:"瘦的；薄的"},
    {en:"run",zh:"跑；奔；流淌"},{en:"cook",zh:"烹饪；煮；烹调；厨师"},
    {en:"helpful",zh:"愿意帮忙的；有益的"},{en:"quiet",zh:"文静的；安静的"},
    {en:"all",zh:"所有；全部；一切"},{en:"need",zh:"需要"},
    {en:"can",zh:"能够；可以；会"},{en:"young",zh:"年轻的；幼小的；青年的"},
    {en:"swim",zh:"游泳；游动"},{en:"girl",zh:"女孩"},
    {en:"everyone",zh:"每人；人人；所有人"},{en:"many",zh:"许多"},
    {en:"thing",zh:"东西；事情"},{en:"such",zh:"这样的；那样的；此类"},
    {en:"as",zh:"作为；像；如同"},{en:"great",zh:"极好的；优秀的；伟大的"},
    {en:"time",zh:"一段时间；次；时间"},{en:"with",zh:"和；有；用"},
    {en:"know",zh:"知道；认识；了解"},{en:"card",zh:"卡片；名片；贺卡"},
    {en:"talk",zh:"谈话；讨论"},{en:"much",zh:"非常；很；十分"},
    {en:"but",zh:"但是；然而"},{en:"really",zh:"确实；真正地"},
    {en:"different",zh:"不同的；各种的"},{en:"Mr.",zh:"先生"},
    {en:"bus",zh:"公共汽车"},{en:"driver",zh:"司机"},
    {en:"woman",zh:"妇女；女性"},{en:"blue",zh:"蓝色的"},
    {en:"dress",zh:"连衣裙"},{en:"policeman",zh:"男警察"},
    {en:"yellow",zh:"黄色的"},{en:"child",zh:"儿童；小孩"},
    {en:"pink",zh:"粉红色的"},{en:"toy",zh:"玩具"},
    {en:"rabbit",zh:"兔子"},{en:"factory",zh:"工厂"},
    {en:"hospital",zh:"医院"},{en:"restaurant",zh:"餐馆；餐厅"},
    {en:"work",zh:"工作；运转；运作"},{en:"people",zh:"人；人们；国民"},
    {en:"there",zh:"在那里；往那里"},{en:"photo",zh:"照片"},
    {en:"of",zh:"属于；关于"},{en:"grandmother",zh:"（外）祖母；奶奶；外婆"}
  ],
  "外研版":   [
    {en:"almost",zh:"几乎，差不多"},{en:"tap",zh:"（用手指）轻拍，轻叩，轻敲"},
    {en:"shake",zh:"摇动"},{en:"classmate",zh:"同班同学"},
    {en:"lonely",zh:"孤单的，寂寞的"},{en:"magic",zh:"有魔力的，神奇的"},
    {en:"joy",zh:"欢欣，愉快，喜悦"},{en:"notebook",zh:"笔记本"},
    {en:"shelf",zh:"搁板，架子"},{en:"leave",zh:"离开"},
    {en:"page",zh:"（书、报纸、文件等的）页，面"},{en:"ending",zh:"（故事、电影、活动等的）结局，结尾"},
    {en:"silent",zh:"不作声的"},{en:"along",zh:"顺着，沿着"},
    {en:"mountain",zh:"高山，山岳"},{en:"road",zh:"路，道路，公路"},
    {en:"handsome",zh:"（男子）英俊的，漂亮的"},{en:"strict",zh:"严格的，严厉的"},
    {en:"follow",zh:"跟着，跟随"},{en:"postman",zh:"邮递员，邮差"},
    {en:"touching",zh:"感人的，动人的"},{en:"son",zh:"儿子"},
    {en:"serve",zh:"为 …… 工作；供职"},{en:"area",zh:"（国家，市镇等的）地区，区域"},
    {en:"absent",zh:"不在的，缺席的"},{en:"seldom",zh:"很少，罕见，不常"},
    {en:"position",zh:"职位，职务"},{en:"carry",zh:"把（某物或某人）带至（新的地点或位置）"},
    {en:"across",zh:"从一边到另一边；穿过"},{en:"memory",zh:"记忆，回忆"},
    {en:"tear",zh:"眼泪，泪水"},{en:"growth",zh:"（性格、智力或情感的）发展，成长"},
    {en:"hide",zh:"把 …… 藏起来，隐藏"},{en:"care",zh:"关心"},
    {en:"hug",zh:"拥抱"},{en:"kiss",zh:"吻"},
    {en:"marry",zh:"结婚；娶；嫁"},{en:"queen",zh:"女王"},
    {en:"pick up",zh:"搭载，接载"},{en:"actress",zh:"女演员"},
    {en:"change",zh:"换（衣服）"},{en:"race",zh:"比赛"},
    {en:"serious",zh:"严重的"},{en:"disease",zh:"疾病，病"},
    {en:"stay",zh:"停留，逗留，留下"},{en:"trailer",zh:"拖车，挂车"},
    {en:"pull",zh:"拉，扯；拖"},{en:"bright",zh:"欢快的；充满生气的"},
    {en:"refuse",zh:"拒绝，回绝"},{en:"result",zh:"结果，后果"}
  ],
  "译林版": [
    {en:"gym",zh:"体育馆"},{en:"building",zh:"楼房；建筑物"},
    {en:"field",zh:"运动场"},{en:"sports field",zh:"体育场"},
    {en:"dining",zh:"吃饭"},{en:"hall",zh:"大厅；礼堂"},
    {en:"dining hall",zh:"食堂；餐厅"},{en:"lab",zh:"实验室"},
    {en:"part",zh:"部分"},{en:"modern",zh:"现代（化）的；先进的"},
    {en:"as well",zh:"也"},{en:"bright",zh:"明亮的"},
    {en:"everyone",zh:"所有人；每人；人人"},{en:"perfect",zh:"完美的"},
    {en:"a.m.",zh:"上午"},{en:"get up",zh:"起床"},
    {en:"activity",zh:"活动"},{en:"housework",zh:"家务劳动；家务事"},
    {en:"homework",zh:"家庭作业"},{en:"weekday",zh:"工作日"},
    {en:"on weekdays",zh:"在工作日"},{en:"usually",zh:"通常地"},
    {en:"jog",zh:"慢跑"},{en:"a little",zh:"一点；少量"},
    {en:"myself",zh:"我自己；亲自"},{en:"enjoy oneself",zh:"玩得痛快；得到乐趣"},
    {en:"first",zh:"第一；首先"},{en:"term",zh:"学期；期"},
    {en:"start",zh:"开始；着手"},{en:"writer",zh:"作家"},
    {en:"teach",zh:"教（课程）；讲授"},{en:"team",zh:"队；组"},
    {en:"form teacher",zh:"班主任"},{en:"show",zh:"演出；展览；音乐会"},
    {en:"grey",zh:"灰色的；灰色"},{en:"different",zh:"不同的"},
    {en:"thousand",zh:"一千"},{en:"fact",zh:"事实"},
    {en:"in fact",zh:"确切地说；事实上"},{en:"borrow",zh:"借"},
    {en:"newspaper",zh:"报纸"},{en:"magazine",zh:"杂志"},
    {en:"else",zh:"其他的；别的"},{en:"care",zh:"关心"},
    {en:"care about",zh:"关心"},{en:"event",zh:"公开活动；发生的事情"},
    {en:"together",zh:"在一起；共同"},{en:"quite",zh:"相当；非常"},
    {en:"large",zh:"大的"},{en:"special",zh:"特殊的；特别的"}
  ],
  "沪教牛津": [
    {en:"peaceful",zh:"安静的；平静的"},{en:"snake",zh:"蛇"},
    {en:"through",zh:"自始至终；从头到尾"},{en:"part",zh:"区域；地区"},
    {en:"article",zh:"文章"},{en:"reason",zh:"原因；理由"},
    {en:"alive",zh:"有生气；有活力"},{en:"sandcastle",zh:"沙堡"},
    {en:"follow",zh:"按……方式发展"},{en:"divide",zh:"(使)分开"},
    {en:"decide",zh:"对……作出抉择；决定"},{en:"crop",zh:"庄稼；作物"},
    {en:"culture",zh:"文化；文明"},{en:"local",zh:"地方的；当地的"},
    {en:"tradition",zh:"传统"},{en:"continue",zh:"持续；继续存在"},
    {en:"have picnics",zh:"野餐"},{en:"work one's land",zh:"耕种土地"},
    {en:"take a trip",zh:"去旅行"},{en:"solar term",zh:"节气"},
    {en:"in fact",zh:"事实上"},{en:"be divided into",zh:"被划分成……"},
    {en:"be based on",zh:"基于……"},{en:"play an important part in",zh:"在……上发挥重要作用"},
    {en:"system",zh:"系统"},{en:"file",zh:"档案"},
    {en:"amazing",zh:"令人大为惊奇的"},{en:"planet",zh:"行星"},
    {en:"billion",zh:"十亿"},{en:"cover",zh:"盖；覆盖"},
    {en:"area",zh:"地区；地域"},{en:"freezing",zh:"极冷的"},
    {en:"north",zh:"北；北方"},{en:"pole",zh:"(行星的)极；地极"},
    {en:"desert",zh:"沙漠；荒漠"},{en:"metre",zh:"米"},
    {en:"reach",zh:"足够达到"},{en:"grain",zh:"谷粒"},
    {en:"wide",zh:"宽的；宽阔的"},{en:"whale",zh:"鲸"},
    {en:"butterfly",zh:"蝴蝶"},{en:"provide",zh:"提供；供应"},
    {en:"explore",zh:"探索"},{en:"disappear",zh:"消失；不见"},
    {en:"plastic",zh:"塑料"},{en:"pollution",zh:"污染"},
    {en:"protect",zh:"保护"},{en:"chemical",zh:"化学制品；化学品"},
    {en:"groundwater",zh:"地下水"},{en:"burn",zh:"燃烧；烧"}
  ],
  "鲁教版":   [
    {en:"go on a school trip",zh:"参加学校郊游"},{en:"visit a museum",zh:"参观博物馆"},
    {en:"see an exhibition",zh:"看展览"},{en:"give directions",zh:"指路"},
    {en:"make progress",zh:"取得进展"},{en:"try on",zh:"试穿；试戴"},
    {en:"write down",zh:"写下；记录"},{en:"fill the basket",zh:"装满篮子"},
    {en:"take notes",zh:"做笔记"},{en:"learn about",zh:"了解；学习"},
    {en:"story",zh:"故事；小说"},{en:"fairy tale",zh:"童话故事"},
    {en:"emperor",zh:"皇帝"},{en:"duckling",zh:"小鸭子"},
    {en:"swan",zh:"天鹅"},{en:"used to",zh:"过去常常（做某事）"},
    {en:"in the past",zh:"在过去"},{en:"at the end",zh:"最后；最终"},
    {en:"be proud of",zh:"为……感到骄傲"},{en:"from...to...",zh:"从……到……"},
    {en:"feather",zh:"羽毛"},{en:"fisherman",zh:"渔夫"},
    {en:"genie",zh:"精灵"},{en:"hunter",zh:"猎人"},
    {en:"net",zh:"网"},{en:"promise",zh:"承诺；答应"},
    {en:"pretend",zh:"假装；伪装"},{en:"silly",zh:"愚蠢的；傻的"},
    {en:"ugly",zh:"丑陋的；难看的"},{en:"brave",zh:"勇敢的"},
    {en:"wise",zh:"明智的；聪明的"},{en:"lie",zh:"撒谎；躺"},
    {en:"bite",zh:"咬；咬伤"},{en:"save",zh:"拯救；节省"},
    {en:"hide",zh:"隐藏；躲藏"},{en:"appear",zh:"出现；显现"},
    {en:"disappear",zh:"消失；不见"},{en:"magic",zh:"奇奇的；魔法"},
    {en:"treasure",zh:"宝藏；财富"},{en:"lesson",zh:"教训；课"},
    {en:"once upon a time",zh:"从前（故事开头用语）"},
    {en:"tell a story",zh:"讲故事"},{en:"retell a story",zh:"复述故事"},
    {en:"make a promise",zh:"许下诺言"},{en:"keep a promise",zh:"信守诺言"}
  ]
};
